adaptlearning/adapt-contrib-core

libraries/backbone.es6.js

part fix for https://github.com/adaptlearning/adapt_framework/issues/3236
* Allow backbone classes to be used in a native ES6 environment
* Use adapt_framework branch [issue/3236](https://github.com/adaptlearning/adapt_framework/tree/issue/3236) [pr#3237](https://github.com/adaptlearning/adapt_framework/pull/3237) remove `ie11` line from [.browserslistrc](https://github.com/adaptlearning/adapt_framework/blob/f46f558ce3b4d03f54751ee0d115947725047e83/.browserslistrc#L9) and `grunt dev`

issue/3236 Add full es6 class support to backbone

---

js/a11y.js

fixes #6 
* `isFocusable, findFocuable, findFirstFocuable` as a set of functions to complement `isReadable, findReadable, findFirstReadable` and `isTabbable, findTabbable, findFirstTabbable`
* `focusNext` and `focusFirst` now use `findFirstFocusable` instead of `findFirstReadable` to excludes grouping elements allowing content to be focused rather than the container
* Return `null` instead of `undefined` for clarity

issue/6 Distinction between readable and focusable for findForward

---

js/router.js
js/scrolling.js
less/core/scrolling.less
schema/config.schema.json

fixes https://github.com/adaptlearning/adapt_framework/issues/2967
alternative to https://github.com/adaptlearning/adapt-contrib-core/pull/15
* The scrolling container will be enabled by default
* Instead of scrolling using the viewport to scroll, Adapt would use the `body` tag to scroll rather than `#app` tag as before 
* The navigation bar can remain fixed position rather than being relative, as it was with the old implementation
* The content can reach from the top of the screen under the navigation bar, to the bottom screen, rather than from under the navigation bar to the bottom of the screen, which brings the behaviour inline in both modes
* The navigation bar width must be offset for the `body` element's scrollbar, this is as unlike the viewport scrollbar the body scrollbar does …

issue/2967-b Scrolling container rewrite

---

js/models/questionModel.js
js/views/questionView.js

fixes #32 
* `_shouldShowMarking` is now set appropriately
* `shouldShowMarking` checks for interactivity
* `isInteractive` on the view

issue/32 Changed shouldShowMarking for jsx

---

js/models/questionModel.js

fixes #41 
* Compile feedback into handlebars template with model json as the context allowing `{{_rawScore}} / {{_maxScore}}`

issue/41 Allow handlebars model properties in feedback

---

js/models/itemsQuestionModel.js
js/models/questionModel.js
js/views/buttonsView.js
js/views/questionView.js

fixes #31 
* Streamlined the call of `resetQuestion` on the view and model
* `resetQuestion` lifecycle function to the model
* Default `resetQuestion` behaviour to the `ItemsComponentModel`

issue/31 Fixed resetQuestion to work with jsx

---

js/data.js

fixes #10 
* Double `routeId` call by removing defer
* Moved startcontroller behaviour into a separate function to make it clearer
* Linting issues
The double call seems to be happening because of [this defer](https://github.com/adaptlearning/adapt-contrib-core/blob/dc9e3c22acd67120d0cb7f7fd844e6df03a16f2e/js/data.js#L171) (which was inherited from [this ancient commit](https://github.com/adaptlearning/adapt-contrib-core/commit/50990850e561f12042446bcc5a4cec7deda3ec85#diff-32cdce28ac549728f6a28999f6d874aa4f29e6da1406c28c3134cd8d421a866aR56) through [here](https://github.com/adaptlearning/adapt-contrib-core/commit/36317b1c9626cd88e6a9dae12fc28694b480f5e6)) and the gap between [`_canNavigate: false`](https://github.com/adaptlearning/adapt-contrib-core/blob/dc9e3c22acd67120d0cb7f7fd844e6df03a …

issue/10-2 Removed defer from startController router change

---

js/views/contentObjectView.js

fixes #22 
part fix for https://github.com/adaptlearning/adapt-contrib-bookmarking/issues/46
part fix for https://github.com/adaptlearning/adapt-contrib-trickle/issues/128
* Throw error when attempting to render past locked content

issue/22 Throw error rendering past locked content

---

js/views/notifyPopupView.js

fixes #62 
* Unusual event listener cause erroneous remove on notify

issue/62 Removed page:scrollTo from notifyPopupView removal

---

templates/header.jsx
templates/partials/component.hbs

fixes https://github.com/adaptlearning/adapt_framework/issues/3197
* Component description is output when no displayTitle, title, body and instruction text are defined.

issue/3197 Output component description when no header is present

---

js/a11y.js

fixes #92 
* Check for aria-label, aria-labelledby or text content before marking [role=heading] as readable

issue/92 Check for readable content in [role=heading]

---

js/a11y/browserFocus.js
js/views/buttonsView.js
templates/buttons.hbs

fixes https://github.com/adaptlearning/adapt_framework/issues/3190
fixes #95 
The focus now moves forward to the marking aria label if the button goes missing.
* Moved the marking aria label to after the submit button to make it readable [3190](https://github.com/adaptlearning/adapt_framework/issues/3190)
* Blur handler now checks for `display: none` and `visibility: hidden` as well as the `[disabled]` attribute

issue/95 Submit display none fix

---

templates/header.jsx

fixes #106 
* Bug with conversion from `html` to `dangerouslySetInnerHTML`

issue/106 Fix missing helper

---

templates/image.jsx

fixes https://github.com/adaptlearning/adapt_framework/issues/3091
fixes https://github.com/adaptlearning/adapt-contrib-graphic/issues/82
* property `longDescriptionId` for specifiying a container id for the image long description
* property `classes` to allow adding classes to the container
* property `id` to allow giving the container an id

issue/3091 Added longDescriptionId, classes and id to image.jsx

---

js/tracking.js

fixes https://github.com/adaptlearning/adapt_framework/issues/1448
* Only report `_onAssessmentFailed` status when no more attempts are possible
Requires https://github.com/adaptlearning/adapt-contrib-assessment/pull/154

issue/1448 Do not report failure if able to retry

---

js/data.js
js/offlineStorage.js

fixes #110 
part of https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/66
* `offlineStorage.clear` function
* Wait in `onLanguageChange` for other extensions to align with the language changes

issue/110 Added offlineStorage.clear

---

js/device.js

fixes #122 
* Orientation classes are now checked on ever resize
* Apple device orientation is calculated on the mismatch of the ratios between the screen and window, apple devices do not rotate the screen height and width on orientation changes but they do report window height and width orientation changes.
* Use window.innerWidth instead of window.screen.width for size calculation as screen.width doesn't account for pixel density

issue/122 Fix orientation reporting

---

js/data.js

part of https://github.com/adaptlearning/adapt_framework/issues/3305
* Support for `course` directory name to be received from grunt through the build.min.js file
1. To change the folder from `course` to `alternative` and test out the code
```sh
git clone https://github.com/adaptlearning/adapt_framework 3305-course
cd 3305-course
git checkout issue/3305
mv src/course src/alternative
adapt devinstall && npm install
cd src/core
git checkout issue/3305
cd ../../
grunt dev --coursedir=alternative
```
2. You will need to find and replace all of the images in the json files from `course/` to `alternative/`

issue/3305 Support for alternative course folder name

---

js/data.js
js/models/adaptModel.js

fixes #130 
* Tracking positions should not be relative to _isTracking === false models
See https://github.com/adaptlearning/adapt-contrib-spoor/pull/237

issue/130 Filter _isTracking === false from trackingPosition API

---

js/views/notifyPopupView.js

fixes #126 
Allows for content to be injected into the dialog, outside of the content, and still be accessible
* Block accessibillity from `.notify__popup` parent, the dialog container, rather than the `.notify__popup` as the dialog content

issue/126 Fixes notify accessibility blocking

---

js/views/contentObjectView.js

fixes #99 
* `aria-labelledby` on main region as it causes the screen reader to unnecessarily read the page heading multiple times in different contexts

issue/99 Removed unnecessary labelledby on main region

---

templates/image.jsx

Resolves https://github.com/adaptlearning/adapt-contrib-core/issues/132
* Converts image container divs to spans
Dependency:
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/150
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/333

Convert image.jsx divs to spans

---

less/core/drawerItem.less
templates/drawer.hbs
templates/drawerItem.hbs

Resolves https://github.com/adaptlearning/adapt-contrib-core/issues/134
* Converted divs to spans in drawer.hbs
* Converted divs to spans in drawerItem.hbs
* Added `display: block;` to `drawer__item-title` and `drawer__item-body` elements to restore their previous visual display

Convert drawer button divs to spans

---

js/a11y.js
js/helpers.js
templates/heading.hbs

fixes #145 
This is backward compatible, using the current defaults will produce the same outcome. Narrative and accordion will need to be updated to pass an id through for automated calculations.
These are static unless overridden by `_ariaLevel` on the content.
```json
"_accessibility": {
"_ariaLevels": {
"_menu": 1,
"_menuGroup": 2,
"_menuItem": 2,
"_page": 1,
"_article": 2,
"_block": 3,
"_component": 4,
"_componentItem": 5,
"_notify": 1
}
}
```
These aria levels are calculated dynamically, based upon the existence of a title on the defined parent and the offset through the tree, unless overridden in the tree by `_ariaLevel`.
```json
"_accessibility": {
"_ariaLevels": {
"_menu": "1",
"_menuGroup": "@menu+1",
"_menuItem": "@menu+1",
"_page": "1",
"_article": "@page+1",
"_block": …
```

issue/145 Automated aria levels

---

schema/content.schema.json

Fixes #160 
This is a new human-readable ID for content objects which will replace the standard `_id` field on course build (useful in instances where the `_id` must be specified in the config of an extension, and is otherwise broken when the course is copied/imported elsewhere).

Add _friendlyId field

---

less/core/nav.less

fixes #123
* Keep skip navigation button onscreen rather than moving it off top. This stops screen readers from scrolling up when the button receives focus

issue/123 Moved skip navigation button onscreen

---

schema/config.model.schema
schema/config.schema.json

fixes [#3312](https://github.com/adaptlearning/adapt_framework/issues/3312)
Allow a 'target' setting on course config to override desired browser compatibility

Added browser support override ability to course config ('targets')

---

js/views/notifyPopupView.js
js/views/notifyView.js

fixes #208
* Notify should not render the subview specified by the `_id` unless `_shouldRenderId = true`

Fix: Add _shouldRenderId to notify api (fixes #208)

---

js/drawer.js
js/tooltips.js
js/views/TooltipView.js
less/core/tooltip.less
schema/course.model.schema
templates/tooltip.jsx

Review in code
* Drawer registers its tooltip from the schema default + json config
* _classes to tooltip object and template
* JSDoc comments in the controller and view
* Size calculations to use a rending life-cycle of display: none, display: block, visibility: hidden and visibility: visible to allowing the size of the tooltip to be calculated before it is displayed
* Position calculations to remove duplication
* Tooltip render to update only when a new tooltip model and $target is selected
* Mouseover show/hide behaviour
* To optional chaining operators where useful
* Tooltip store from array to object for by id index
* Position application now goes through model into jsx instead of jquery
* Linted
* `TooltipContainerView` in favour of a permenant `TooltipView`
* Global tooltips in …

Refactored branch issue/193

---

js/models/questionModel.js
templates/notifyPopup.hbs

fixes https://github.com/adaptlearning/adapt-contrib-core/issues/173
* Provide an alternative heading for Assistive Technology if no visual heading is required

Update: provide alternative heading for AT (fixes #173)

---

js/a11y.js

Fixes #220
* Removes tabindex from a11y.toggleEnabled
1. Add a Hotgraphic component to a course.
2. Click on an item to open the Notify popup.
3. The disabled buttons should be focusable. Requires https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/241

Update: Remove tabindex from a11y.toggleEnabled (fixes #220)

---

templates/heading.hbs

* Status indicators in the aria-label should come first. Additionally, without context as to what is the status is reporting on can cause confusion as to the purpose of the status indicators. It was agreed the best path forward was to present all aria-headers in the following format:
* [context (if applicable)] [status]. [title]
1. Grab latest PR
2. Grab latest PR from course.json updates …

Update: Adds context to status indicators (fixes #151)

---

js/views/notifyPushView.js
js/views/notifyView.js
templates/notify.hbs

fixes #181 
* Notify create `a11y-push` using `notify.create({ _type: 'a11y-push', body: 'Read me as an alert' })` to provide screen reader alerts
* Made toast notifications appear above normal notify

New: Added accessible alert api (fixes #181)

---

templates/notifyPopup.hbs
templates/notifyPush.hbs

#202 
* replace deprecated a11y_attrs_heading usage
See https://github.com/adaptlearning/adapt-contrib-tutor/compare/issue/67

Fix: replace deprecated a11y_attrs_heading usage (fixes #202)

---

schema/config.model.schema

Fixes #162
Update to the legacy schema to work in conjunction with the new relative string values.
Also removed required validator config, as it;s not necessary when using a default value.
See https://github.com/adaptlearning/adapt-contrib-core/pull/146

Fix: Update _ariaLevels defaults to use relative strings (fixes #162)

---

js/a11y.js

Fixes #233
* Change nullish coalescing operator to logical OR for ariaLevel check, so that 0 is not accepted as a level value.

Fix: aria-level is set to "0" for headings (fixes #233)

---

js/views/headingView.js
templates/article.hbs
templates/block.hbs
templates/header.jsx
templates/heading.hbs
templates/page.hbs
templates/partials/component.hbs

fixes #235 
Instead of using semantic heading levels, as this requires a lot of styling fixes in vanilla, I've focused more on making the headings clickable and unified, rather than having a separate heading for accessibility.
* Unify accessible and display headings
Requires 
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/152
https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/127

Fix: Made headings clickable

---

js/helpers.js
js/models/itemsQuestionModel.js
js/models/questionModel.js
less/core/notify.less
templates/notifyPopup.hbs

fixes #222 
This behaviour is fully backward compatible if the old style of `_feedback` objects are used. The new style feedback can be used in the new AAT and if building by hand, it will not be supported in the classic AAT
* Added object style for feedback states, at `_feedback._correct`, `_feedback._partlyCorrectNotFinal`, `_feedback._partlyCorrectFinal`, `_feedback._incorrectNotFinal` ,`_feedback._incorrectFinal` and for `_items[].feedback`
```json
{
"altTitle": "",
"title": "",
"body": "Incorrect feedback final",
"_classes": "",
"_imageAlignment": "left",
"_graphic": {
"_src": "course/en/images/single-width.png",
"alt": "test",
"attribution": ""
}
}
```
* QuestionModel functions to be replaced with simpler getFeedback function
* setupCorrectFeedback
* setupPartlyCorrectFeedback
* …

Fix: Expanded feedback to add images and more control (fixes #222)

---

js/data.js
js/models/adaptModel.js

Ensures no fallover when parent is empty
Fixes [#248](https://github.com/adaptlearning/adapt-contrib-core/issues/248)
* logging.warn of empty parent object on fetch
* Updated console.warns to go through the Logging class in a few places
1. Create a basic 2 page course with blank components on each
2. Add Trickle and LanguagePicker extension
3. Add second language
4. Start the course and enter a page
5. Change language
###Broken behaviour
Language switch fails
Screen JS becomes broken (incomplete rendering etc)
###New behaviour
Console warning indicates no parent available
Screen renders menu view for new language

Fix: Core cannot find parent on language change triggered by trickle

---

less/core/component.less

Fixes: #263 
* Changed component right rtl margin-left value from `inherit` to `0` to resolve visual offset error

Fix: Changed component right rtl margin-left value (fixes #263)

---

js/reactHelpers.js

Fixes #270 
* Passes in the 'this' keyword to the call() function in helper().
Refer to #270

Fix: helper() function in reactHelpers (fixes #270)

---

js/views/navigationView.js
less/core/nav.less
schema/course.model.schema
schema/course.schema.json
templates/nav.hbs

fixes #238
requires https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/151
requires https://github.com/adaptlearning/adapt_framework/pull/3332
The dom order and visual order will be aligned, such that the screen reader read order is correct.
* Moved from `float` styling to `flex`
* Added spacers
* Added default schema order for buttons and spacers
* Reorder happens when any child is changed

Fix: Navigation button read order (fixes #238)

---

js/models/adaptModel.js

Fixes #279.
* Account for every child being `_isOptional` when checking/setting completion.

Fix: `_isOptional` completion

---

js/views/adaptView.js
js/views/questionView.js

fixes #257 
* Allow plugins to pause rendering
* Stop and start rendering in `onSubmitClicked` handler to reduce cpu usage

Fix: Allow plugins to pause rendering (fixes #257)

---

schema/course.model.schema

Fix: missing `inputType` for `_navOrder` in course.model.schema

---

js/views/adaptView.js

Fixes #259.
* Added model `_type` to the `view:addChild` and `view:childAdded` events, so listeners can be setup for specific model types.

New: ChildView API events

---

js/views/buttonsView.js

Fixes #265
* Add another event listener for when `feedbackTitle` changes. This allows the feedback button to be enabled when the feedback content only has a title and no body text.
* `onFeedbackMessageChanged()` is now only concerned with _enabling_ (not disabling) the Feedback button.
* In `refresh()`, use the new method `disableFeedbackButton()` instead of `onFeedbackMessageChanged()`.
1. Include the following feedback in a question:
```
"_feedback": {
"altTitle": "",
"title": "Feedback global title",
"_classes": "",
"_correct": {
"altTitle": "",
"title": "Correct feedback title",
"body": ""
},
"_incorrectNotFinal": {
"altTitle": "",
"title": "",
"body": "Incorrect feedback body, not final"
},
"_incorrectFinal": {
"altTitle": "",
"title": "",
"body": "Incorrect feedback body, final"
} …
```

Fix: Enable Show Feedback button when feedback content only has a title (fixes #265)

---

js/models/questionModel.js

The previous fix did not account for falsey values as defaults on destructured properties only get set for incoming 'undefined' values
Fixes: #310 
* Destructured _feedback props now overwritten, even if empty string (not just undefined)

Fix: Correct appllication of fallback values for feedback title

---

js/views/drawerView.js

fixes #312 
* Drawer wasn't setting its position on multi-extension button menu view

Fix: Set drawer position on multi-extension button menu view

---

templates/header.jsx
templates/partials/component.hbs

Fixes #328 
* Adds a `span` element with an `icon` class. This can be used to show an icon when, for instance, the instruction text should be highlighted as an error.
Can be tested along with https://github.com/adaptlearning/adapt-contrib-narrative/pull/250 .
1. Add a Narrative component
2. On mobile, click the Next button without first clicking on the strapline button.
- All styling for this error message / icon currently lives in the Narrative component's Less. We could consider moving it to the theme or core styles, though.

New: Add icon span to instruction element in header.jsx (fixes #328)

---

js/a11y.js
js/a11y/popup.js
js/a11y/scroll.js

fixes #307 
* Allow up, down, home, end, pageUp and pageDown to scroll popups
* Added `core/js/a11y` `isPopupOpen` and `popupStack`

New: Allow up, down, home, end, pageUp and pageDown to scroll popups (fixes #307)

---

js/tracking.js
schema/config.model.schema
schema/config.schema.json

Fixes #112 
Fixes https://github.com/adaptlearning/adapt-contrib-spoor/issues/262
* Update tracking logic to account for [Scoring API](https://github.com/adaptlearning/adapt-contrib-scoring)
* Allow `tracking:complete` to be triggered for every assessment attempt, if required

New: Update tracking logic to account for Scoring API

---

js/models/lockingModel.js

fixes #319 
* Detect initial defaults set and prevent warning from appearing

Fix: Removed locking model error on defaults set

---

js/fixes.js
js/fixes/safari.label.click.blur.js

fixes #350 
* General fix for safari label clicks to redirected the label click, to an input click, which overcomes complex brower+react bug
Please test on ios and macos safari and on windows chrome, edge and firefox if you can.
Requires https://github.com/adaptlearning/adapt-contrib-mcq/pull/206

Fix: Safari label click for input

---

js/a11y.js
js/a11y/browserConfig.js

fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/386
* Added an `is-prefers-reduced-motion` class to the html tag only when [`_isPrefersReducedMotionEnabled`](https://github.com/adaptlearning/adapt_framework/pull/3387) and `prefers-reduced-motion` is set in the browser.
References:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/reduced-motion-simulation

New: Added is-prefers-reduced-motion html class and _isPrefersReducedMotionEnabled a11y option

---

js/fixes/safari.label.click.blur.js

fixes #353 
* Allow browser to search for elements by id when using invalid AAT ids
* Prevent any other click-crash if specified id cannot be found

Fix: Safari fix invalid AAT ids (fixes #353)

---

js/views/adaptView.js

fixes https://github.com/adaptlearning/adapt-contrib-branching/issues/43
* Previous [pr](https://github.com/adaptlearning/adapt-contrib-core/pull/281) broke API where variable `model` doesn't exist.
https://github.com/adaptlearning/adapt-contrib-core/blob/3668a15c1e9777c23615746cd1d8465f9d729a27/js/views/adaptView.js#L299

Fix: ChildView API broken

---

js/views/buttonsView.js

Fixes [issue/356](https://github.com/adaptlearning/adapt-contrib-core/issues/356)

Fix: Ensure marking appears only when canShowMarking is enabled

---

js/a11y/scroll.js

fixes #367 
Tested on Chrome Android and Windows with mousewheel, touch and keyboard interactions.
* Fixed typo in previous commit https://github.com/adaptlearning/adapt-contrib-core/commit/18391922a770faeea65564d5bcd0a3170cf77ecd
* In order to sidestep Safari 16.4 issues, DOM event attachment is permanent and returned early rather than toggled attached and removed

Fix: Scroll background from popups

---

js/device.js
less/_defaults/_variables.less
schema/config.model.schema
schema/config.schema.json
templates/header.jsx
templates/image.jsx

fixes #371 
Alternative to https://github.com/adaptlearning/adapt-contrib-core/pull/373
* Add `xlarge` default to schemas starting at 1280
* Add `device.isScreenSizeMin(name)` to return true/false if the device is equal or above the named screen size
* Adjusted the breakpoints and schema descriptions so that it's clear that the breakpoint values are for the bottom of each named boundary according to https://github.com/adaptlearning/adapt-contrib-core/issues/364#issuecomment-1544268315
* Recalculated `size-` classes were not derivable
* `mobileInstruction` now only appears at `small`, to account for the `small` > `medium` change in hotgraphic and narrative
* When **only** `small` and `large` images are defined, images  switch from `small` to `large` at `medium` or above to better fit the …

New: Added xlarge breakpoint, added isScreenSizeMin

---

js/reactHelpers.js

fixes #374 
* reactHelpers.helper passes through correct this context for handlebars helpers

Fix: reactHelpers.helper pass through correct this context

---

js/models/itemsQuestionModel.js

fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/171
Allows only incorrect answers to reset instead of all answers.
* Added `_shouldResetAllAnswers ` as an `ItemsQuestionModel` settings

Fix: _shouldResetAllAnswers moved into core from matching

---

js/collections/notifyPushCollection.js
js/views/notifyView.js
templates/notifyPush.hbs

fixes #376 
* Hide close button on a11y-push notify
* Support `_showCloseButton` on push notifications

Fix: Hide close button on a11y-push notify

---

templates/image.jsx

Fixes #402
* Adds option for the HTML attribute `draggable`
1. Where the image.jsx template is used, add the draggable property. For example:
```
<templates.image {..._graphic}
draggable="false"
/>
```
2. If `draggable` is set, it should include the property on the `<img>` tag.
3. If `draggable` is not set, it should _not_ include the property on the `<img>` tag.
This will be used in https://github.com/adaptlearning/adapt-contrib-narrative/pull/270, so it can also be tested there.

Fix: Add draggable attribute option (fixes #402)

---

js/views/questionView.js

Fixes #391 
* Create `focusAfterReset()` which moves the focus behavior from `onResetClicked()`. This makes it simpler to override the focus behavior in a plugin.

Fix: Create focusAfterReset to move focus behavior from onResetClicked (fix #391)

---

js/views/adaptView.js

Fixes #405 
* Return `null` in `getChildViews()` if `this._childViews` is undefined. Minor fix for code readability.

Fix: Return null in getChildViews if this._childViews is undefined (fix #405)

---

js/views/buttonsView.js

Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/390
* The class `is-full-width` was not being applied to the `js-btn-marking` icon when it should have, meaning that it was appearing in the center, when it should have been to the right of the full width button.
1. In any question component set `_canShowMarking` to true and `_canShowFeedback` to False.
2. Complete the question and confirm that the icon is on the right
3. Keep testing with other configurations of these settings to confirm that they all work correctly.

Fix: Missing is-full-width class

---

js/models/questionModel.js

* Removed multiple ternaries
* Remove switch statement
* Enclosed new function
* Removed duplicate behaviour

Further refactor

---

js/models/questionModel.js

Fixes #415 
* 'Partly Correct Not Final' feedback should fall back to 'Partly Correct Final' which in turn should fall back to 'Incorrect Final' as per instruction text

Fix: PartlyCorrect feedback fallback values

---

templates/image.jsx

Resolves: #396 
* Added a new class to image template, to be based on `_srcFocalPoint` value that's part of the `_graphic` object

New: Added new _srcFocalPoint class to image.jsx (fixes #396)

---

js/models/questionModel.js

Currently if no feedback title is given the questionModel will return the components display title/title meaning that the altTitle isn't used unless all of the feedback/component titles are empty. 
My suggestion is to remove the components display title/title as fallbacks so if no feedback title is given the altTitle is used for screen readers with no visible feedback title. 
Original issue - #411 
* remove component diplayTitle and Title …

Fix: remove component diplayTitle and Title fallbacks for feedbackTitle

---

libraries/enum.js

fixes #436 
* Refactor to ES6
* Fix alias enumeration behaviour
* Added `toString()` which is more standard than `asString`
* Exposed `lookupHash` for easy debugging

Fix: ENUM refactor, linting and fix aliases (fixes #436)

---

js/router.js

#431 
* focusFirst on document.body when navigating to a contentObject (fixes #431)

Fix: focusFirst on document.body when navigating to a contentObject (#431)

---

less/core/drawer.less

Fix #444 
* Fixes the drawer's Back button position when using an RTL language
See notes in #444

Fix: Drawer Back button position when using an RTL language (fixes #444)

---

templates/notifyPopup.hbs

Fix #450 
* Notify popup template - Compile the `_graphic.attribution` property so that Handlebars helpers can be used in the content.
Add a helper to the `_graphic.attribution` property in a feedback popup.
Example helper:
```
{{a11y_alt_text '$5bn' 'five billion dollars'}}
```
Example `_feedback`:
```
"_feedback": {
"altTitle": "",
"title": "Feedback",
"_classes": "",
"_correct": {
"altTitle": "",
"title": "Well done!",
"body": "",
"_classes": "notify-graphic-with-score",
"_imageAlignment": "right",
"_graphic": {
"alt": "5 billion dollars",
"_src": "assets/5-billion.png",
"attribution": "{{a11y_alt_text '$5bn' 'five billion dollars'}}"
}
},
```

Fix: Notify popup - Compile _graphic.attribution (fixes #450)

---

js/models/questionModel.js

fixes #457 
* Added `_isPartlyCorrect` to storage mechanism
* Answer the mcq `c-60`
* Use the console to check that `_isPartlyCorrect` was stored in the attempt object

Fix: Added _isPartlyCorrect to storage mechanism (fixes #457)

---

schema/article.model.schema
schema/block.model.schema
schema/component.model.schema
schema/component.schema.json
schema/content.schema.json
schema/contentobject.model.schema
schema/course.model.schema
templates/header.jsx

- Replace legacy [`_disableAccessibleState`](https://github.com/adaptlearning/adapt-contrib-core/issues/186#issuecomment-1193742040) with `_isA11yCompletionDescriptionEnabled` in component schemas.
- Remove reference to legacy `_disableAccessibilityState`.
- Add missing `_isA11yCompletionDescriptionEnabled` to schemas.
Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/246
[Wiki](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes#component-model-attributes) updated in advance - `_isA11yCompletionDescriptionEnabled` added to the relevant models.

Fix: Add _isA11yCompletionDescriptionEnabled to schema and remove legacy _disableAccessibilityState (fixes #246)

---

js/views/TooltipView.js
js/views/navigationView.js

fixes #429 #463 
Tooltips functionality adds aria-labelledby to the mouseover element. In the navigation bar modifying any child element causes the navigation bar to attempt to correctly sort its children. In firefox, moving an element by reordering it causes the mouseover event to refire.  A tooltip is shown every time a mouseover event is fired.
* Stop the navigation bar children from reordering if they do not need to
* Stop a tooltip showing if it is already showing
* Ensure a tooltip is hidden when any element is clicked

Fix: Firefox multiple tooltips (fixes #429)

---

js/router.js

Fixes #399.
* Incorrect `scrolledTo` event name which was preventing this from being used by listeners.

Fix: incorrect `scrolledTo` event name (fixes #399).

---

schema/article.model.schema
schema/block.model.schema
schema/component.model.schema
schema/content.schema.json
schema/contentobject.model.schema

`_ariaLevel` override removed from the page/article/block/component schemas. 
Since `_ariaLevels` were [automated in Core](https://github.com/adaptlearning/adapt-contrib-core/pull/146), there's no need to manually override these now.
Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/442
[Wiki](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes) updated.

Update: Remove _ariaLevel override property (fixes #442)

---

js/a11y.js

fixes #472 
* a11y.isReadable and therefore a11y.isFocusable returns false if element is not in the body tag

Fix: Detached elements are not focusable or readable (fixes #472)

---

templates/notifyPopup.hbs

Don't render `.notify__section` unless `_graphic.src` and/or `body` exists.
Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/476
**Question**
Just something I noticed during this PR. Does anyone know what the `~` is used for in the [notifyPopup.hbs](https://github.com/adaptlearning/adapt-contrib-core/blob/535905f91b1dfca190179f6e6ef2909e020f0efb/templates/notifyPopup.hbs#L56) conditions? 
In core, this is the only hbs file using it.

Update: Prevent Notify popup rendering empty .notify__section container (fixes #476)

---

js/a11y/browserFocus.js

fixes #486 
* Stop auto next focus unless focus is returning to the body from a disabled or hidden element

Fix: Auto focus next only when returning to body from disabled or hidden (fixes #486)

---

js/models/itemsComponentModel.js

fixes #493 
* Call storeUserAnswer on item change

Fix: Call storeUserAnswer on item change (fixes #493)

---

js/models/itemsComponentModel.js

fixes #489
* Ensure that save/restore of useranswer in ItemsComponentModel is index aware

Fix: useranswer save/restore _index awareness (fixes #489)

---

js/a11y.js
js/views/headingView.js

fixes #453 
* Moved course to menu conversion back in the execution hierarchy to allow [a11y.ariaLevel](https://github.com/adaptlearning/adapt-contrib-core/blob/8b36e3ee68941b62e711198f49fa9345c1758132/js/a11y.js#L187) to convert course type to menu instead of relying on [headingView](https://github.com/adaptlearning/adapt-contrib-core/blob/8b36e3ee68941b62e711198f49fa9345c1758132/js/views/headingView.js#L18) to do it.

Fix: Support level course in a11y.ariaLevel (fixes #453)

---

less/core/nav.less

#443 
* Ignore .nav__skip-btn when hiding nav button labels (fixes #443)

Fix: Ignore .nav__skip-btn when hiding nav button labels (fixes #443)

---

js/headings.js
js/views/adaptView.js
js/views/headingView.js

fixes #516 
* Added view remove events, `preRemove`, `remove` and `postRemove`
* HeadingView is destroyed when parent view is destroyed

New: Added view remove events, attached HeadingView

---

js/models/questionModel.js
templates/notifyPopup.hbs

Fixes #509 
* Fallback value of title used for component feedback when _feedback.title not set

Fix: Fallback value of title used for component feedback when _feedback.title not set (509)

---

js/deprecated.js
js/scrolling.js

fixes #513
* Changed error from `src/core/offlineStorage` and `src/core/wait` to `core/js/offlineStorage` and `core/js/wait`
* Changed scrolling to refer to the singleton directly rather than through Adapt.scrolling

Fix: deprecated.js src/core to core/js (fixes #513)

---

js/models/itemModel.js
js/models/itemsQuestionModel.js

_isActive property always expected to be boolean but toggleActive not strictly enforcing this currently
enforcing type boolean on _isActive within toggleActive function

Fix: enforcing type boolean on _isActive (Fixes #523)

---

js/views/contentObjectView.js

fixes #516 
* Added preRemove and remove events to contentObjectView

Fix: Added preRemove and remove events to contentObjectView

---

templates/nav.hbs

Fixes #534 
**Note:** This PR is considered a stopgap until #512 is completed.
Sets defaults for the Drawer navigation button:
* Set a default [icon](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Icons#icons-in-adapt) of `icon-list` for the `_iconClass` property. The icon will no longer be hidden if `_iconClass` is not set.
* Set a default `_position` of `auto`
In _config.json_, configure the `_drawer` object with _and_ without values for `_iconClass` and `_position`. When not set, it should show the list icon and the position should be `auto`.
```
"_drawer": {
"_showEasing": "easeOutQuart",
"_hideEasing": "easeInQuart",
"_duration": 400,
"_position": "right",
"_iconClass": "icon-folder"
},
```

Fix: Add default values for Drawer button icon and position (fixes #534)

---

templates/image.jsx

Fix #544 
* Use `dangerouslySetInnerHTML` to set the attribution text in _image.jsx_
* Compile attribution text so that we can use helpers
1. In a Graphic component, set the `_graphic.attribution` value to:
```
{{a11y_alt_text '$5bn' 'five billion dollars'}}
```
2. The attribution text should read `$5bn` with a hidden aria-label of `five billion dollars`
```
<span class="component__attribution graphic__attribution">
<span class="component__attribution-inner graphic__attribution-inner">
<span aria-hidden="true">$5bn</span>
<span class="aria-label">five billion dollars</span>
</span>
</span>
```

Fix: Use dangerouslySetInnerHTML to set attribution text in image.jsx (fixes #544)

---

js/transitions.js

Fixes #533.
* Handler to `await` completion of active `CSSTransitions` at point of execution.

New: event handler for CSS transitions

---

templates/header.jsx
templates/partials/component.hbs

Fix #538 
* Introduces the `mobileBody` property for component headers
1. Add a `body` and `mobileBody` value to any component.
2. Switch to mobile view (less than medium breakpoint) and ensure that body text uses `mobileBody` instead of `body`.
3. Switch back to desktop view (medium breakpoint or higher) and ensure that body text uses `body` instead of `mobileBody`.
Add `mobileBody` and `mobileInstruction` to the core component schemas. Then, remove them from the schemas of components like [Hot Graphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/55b26b7fdae55f6c3d97384da2bd39e2d45e6616/schema/component.schema.json#L78) and [Narrative](https://github.com/adaptlearning/adapt-contrib-narrative/blob/c350f7610a0ee927a1259efdd2623e46e2847e94/schema/component.schema.json#L35) …

New: Allow any component to use mobileBody for smaller devices (fixes #538)

---

js/views/adaptView.js

Fixes: #549
* Allow for instance template overrides
```js
class TestView extends ComponentView {
get template() {
return 'templateName.jsx';
}
}
```
instead of:
```js
class TestView extends ComponentView {
// ...
}
TestView.template = 'templateName.jsx';
```

New: Allow for instance template overrides (fixes #549)

---

js/views/TooltipView.js

related https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/304
This allows safari to catch up on the initial position of the static tooltips, showing them in the correct place.
* Show static tooltips at end of event loop always

Fix: Show static tooltips at end of event loop always

---

js/views/buttonsView.js

Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/553
Requires `answeredPartlyCorrect` aria label added to course __globals_  (FW PR https://github.com/adaptlearning/adapt_framework/pull/3570).
You can test the following either by running a screen reader or inspect the button marking label `.js-btn-marking-label` (button marking displays bewteen the _show answer_ / _feedback_ buttons.
1. Test with FW branch [issue/3565](https://github.com/adaptlearning/adapt_framework/tree/issue/3565)
2. Using the Adapt course, go to Matching component c-225.
3. Answer the Matching component as per below to test correct, partially correct and incorrect aria labels are used. 
- correct answers - item 1: 2013, item 2: 2008, item 3: Hebrew
- partly correct answers - item 1: 2013, item 2: 2013, …

New: aria label added for partly correct answers (fixes #553)

---

js/a11y.js

Fixes: #547 
* Include explicitly set `_ariaLevel` in relative offset calculation.

Fix: Include explicitly set ariaLevel (fixes #547)

---

js/views/headingView.js
templates/heading.hbs

Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/561
Added `.js-a11y-completion-description` selector to heading completion aria-label instead of targeting generic `.aria-label` selector to update completion. 
This will prevent functionality clashes between elements of a shared selector. For example, using `a11y_alt_text` [helper](https://github.com/adaptlearning/adapt-contrib-core/blob/0e1fe9e23853421b90dacbd5bb886caf24df7c8b/js/helpers.js#L364) within a `displayTitle`, as per the associated issue.
1. Use the `a11y_alt_text` helper within a `displayTitle`. Note, you'll need to test this on a component that requires interaction rather than in view completion. For example, an Accordion title.
`"displayTitle": "I wish I had {{a11y_alt_text '$5bn' 'five billion dollars'}}",` …

Fix: heading completion selector added to aria-label (fixes #561)

---

js/router.js

fixes #569 
* Do not trigger a `router:location` event when `router.updateLocation` is called without changing location

Fix: Do not trigger location update when location hasn't changed (fixes #569)

---

js/fixes/img.lazyload.js
js/models/itemsComponentModel.js
js/router.js
js/views/buttonsView.js
js/views/menuItemView.js

Fix #571 
* Fixes minor JavaScript linting issues 
* Fix `hasOwnProperty` warning in _img.lazyload.js_

Fix: Resolve minor JavaScript linting issues and hasOwnProperty warning (fixes #571)

---

templates/image.jsx

Fix #574 
* Removes the `aria-label` attribute from images when alt text is empty
In plugins that use the core `image.jsx` template (e.g. the [Graphic](https://github.com/adaptlearning/adapt-contrib-graphic) component), set the `alt` property in the JSON config to an empty string. The `aria-label` attribute should not be present.

Fix: Remove aria-label from images when alt text is empty (fixes #574)

---

schema/component.schema.json
schema/content.schema.json
schema/contentobject.schema.json
schema/course.schema.json

#580 
ref: The update in schemas is needed to ensure that default displayTitles are not applied to articles and blocks to speed up AAT workflow. As discussed legacy schemas are to be left with existing functionality. 
* DisplayTitle default removed from content and moved to specific schemas (fixes #580)

Fix: DisplayTitle default removed from content and moved to specific schemas (fixes #580)

---

js/views/TooltipItemView.js
js/views/adaptView.js

fixes https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/319
When animating the parent of a tooltip, the tooltip will follow the parent element.
* Introduce animation loop for tooltip movement, triggered on onscreen animationStart, contentObjectView:ready and device:resize
* Add an onscreen animation to the hotgraphic's block and scroll it into view

Fix: Allow tooltips to follow animations

---

js/views/contentObjectView.js
js/views/notifyPopupView.js
libraries/inview.js

fixes #578
* Use browser API [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) to reduce code complexity and increase performance
Refs:
* https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver
* https://caniuse.com/intersectionobserver
Note:
* Not ie11 compatible

Update: inview.js to use IntersectionObserver

---

js/models/adaptModel.js
js/models/lockingModel.js
js/models/questionModel.js

part of #584 
* _isLocked becomes a lockable attribute allowing plugins to force _isLocked: true
* Do not lock when setting initial defaults (this can occur when cloning a model)
* Make sure to copy locked attribute states on ComponentModel.deepClone
* Clarified QuestionModel._canSubmit locking as model properties rather than an init function call
* The core will softly warn to the console in the period between this change and changing other plugins (trickle) to provide their pluginName when setting _isLocked.
requires https://github.com/adaptlearning/adapt-contrib-trickle/pull/231

New: _isLocked becomes a lockable attribute

---

libraries/inview.js

fixes #588 
* Moved item processing into one unified function making the rules clearer
* Fixed locking so that it processes correctly on unlocks
* Fixed locking so that adds and removes potential duplicate locks correctly

Fix: Inview locking and triggering (fixes #588)

---

less/core/notify.less
templates/notifyPopup.hbs

Fix #586 
* Moves the notify title directly above the body text
* Applies to Notify popups that use `notifyPopup.hbs`
* Adds a `.notify__text` wrapper to the body and text area
1. Should this be a configuration option or just the default behavior?
2. Are there any use cases that this will break?
3. What are the disadvantages for using this layout? Is it a bad idea?
1. Add feedback with images. For example:
```
"_feedback": {
"title": "Feedback",
"_correct": {
"title": "Correct feedback text.",
"body": "That’s correct. Aliquip id nisi sunt do sint. Laboris nisi nisi Lorem tempor non proident. Nulla laboris ad incididunt irure officia cillum incididunt esse sunt laborum.",
"_imageAlignment": "left",
"_graphic": {
"_src": "course/en/images/correct.jpg",
"alt": "Correct"
}
}, …
```

Update: Move notify title above body text (fix #586)

---

js/modelHelpers.js
js/models/adaptModel.js
js/models/itemModel.js

fixes #592 
* `toggleModelClass(model, className, hasClass)` in `modelHelpers.js`
* `AdaptModel.prototype.toggleClass(className, hasClass)`
* `ItemModel.prototype.toggleClass(className, hasClass)`

New: Added toggleClass to AdaptModel and ItemModel

---

js/views/questionView.js

Fix #594 
* Adds the error class `has-error` to question components when the question cannot be submitted.
1. Install and enable [Instruction Error](https://github.com/adaptlearning/adapt-contrib-instructionError) which will allow you to submit a question before it is completed (ex. before an option is selected in an MCQ)
2. Select the "Submit" button before making a choice
3. The component should now have the `has-error` class.
4. Next, make a selection for the question. If the question has multiple items (e.g. Matching), make a selection for every item.
5. Select the "Submit" button
6. The `has-error` class should be removed.

New: Add "has-error" class for use with question components (fixes #594)

---

libraries/inview.js

fixes #596 
Inview was using old window dimensions to measure inview positions. These must be recalculated when the window is resized.
* Trigger reprocess on window resize

Fix: inview reprocess on window resize (fixes #596)

---

js/a11y/popup.js

fixes #616 
* Enable popup support when config.json:`_accessibility._isEnabled: false`

Fix: Popup support in a11y disabled (fixes #616)

---

js/deprecated.js
js/views/drawerView.js
js/views/notifyPopupView.js

Additional fixes to pr https://github.com/adaptlearning/adapt-contrib-core/pull/601
fixes #619 
fixes #620 
* Re-added the `focusFirst` calls removed in #601 to force the focus management of notify and drawer open, for issue #620
* Changed all escape key `keyup` handlers to `keydown` in order to better trap the even with screen readers
* Changed from `click` to `mousedown` for shadow click detection
* Changed the order of drawer close animation relative to the `dialog` element `close` function call, to fix #619
* Better support for deprecated [`drawer:closeDrawer` event used by pagelevelprogress](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/b9664407e0b1fd3a3bf75c069c006dbc0a215560/js/PageLevelProgressView.js#L41-L55) to ensure that the correct element is focused …

Fix: Drawer close animation. Drawer and notify open focus

---

js/a11y.js
js/a11y/ariaDisabled.js
js/a11y/browserFocus.js

fixes #623 
* Prevent label clicks and key presses from changing [aria-disabled] inputs
* Move aria-disabled handling into its own controller.

Fix: Prevent label clicks and keypresses from changing [aria-disabled] inputs (fixes #623)

---

less/core/accessibility.less

fixes #606
* Updated `.aria-label` per discussion in #606

Fix: aria-label class not properly hidden (fixes #606)

---

js/views/drawerView.js

Additional fixes to pr https://github.com/adaptlearning/adapt-contrib-core/pull/601
fixes #628 
When plp navigates to a different page it causes both the drawer to close and the pip notify to open. The drawer dialog should be closed before the notify is open such that the drawer close doesn't accidentally close the new notify at https://github.com/adaptlearning/adapt-contrib-core/blob/230a2fa1ae12b6f1e854cb98964fc540286c55b7/js/a11y/popup.js#L168-L176
Reverting to previous behaviour in v6.60.2
https://github.com/adaptlearning/adapt-contrib-core/blob/a1b6c57f8608d0a38ef6918ce3bc9bad6961f580/js/views/drawerView.js#L194-L198
* Perform HTMLDialogElement.close on drawer before animating closed

Fix: Perform HTMLDialogElement.close on drawer before animating closed (fixes #628)

---

js/models/menuModel.js

Fix: Supplying pluginName on updating menu locking (Fixes #638)

---

js/drawer.js
js/views/drawerView.js

fixes #648 
Additional fixes to pr https://github.com/adaptlearning/adapt-contrib-core/pull/601
Further fix to https://github.com/adaptlearning/adapt-contrib-core/pull/629
* Testing works as expected when dialog is closed immediately on navigation
* Force dialog to remain on screen when `HTMLDialogElement.close()` is called

Fix: Force dialog to close synchronously on page navigation (fixes #648)

---

libraries/inview.js

Fixes #630.
* Trigger `inview` and `onscreen` events when element off screen

Fix: trigger `inview` and `onscreen` events when element off screen

---

less/core/accessibility.less

fixes #635
* Add scroll padding to `body` to avoid focus from being obscured by navbar
1. Press tab to move focus to a focusable element.
2. Scroll the page so that the next or previous (depending on `_isBottomOnTouchDevices`) focusable element is positioned behind the navigation bar (but within the viewport).
3. Press (shift) tab  to move focus to the obscured element
4. Confirm that the browser scrolls the focused element into view
Reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top

Fix: add scroll padding to body to avoid focus obscured issue (fixes #635

---

js/data.js
required/index.html

part of https://github.com/adaptlearning/adapt_framework/issues/3649
requires  https://github.com/adaptlearning/adapt_framework/pull/3650
requires https://github.com/adaptlearning/adapt-contrib-spoor/pull/336
* Force download `build.min.js` for fresh `Adapt.build.get('timestamp')`
* Force fresh json according to `Adapt.build.get('timestamp')`
* Force fresh css according to `@@build.timestamp`

New: Use build.timestamp to force json reload

---

js/a11y.js
js/a11y/topOfContentObject.js
js/a11y/topOfPage.js
less/core/accessibility.less
less/core/nav.less
schema/course.model.schema
schema/course.schema.json

fixes #626 
a working alternative to #627 
Notifies the screen reader that a new content object is loaded, allows tabbing and arrowing forward onto the skip navigation button as well as scrolling with the arrow keys without a screen reader. Text is configurable at `_globals._accessibility._ariaLabels.topOfContentObject = '{{type}} {{displayTitle}}'`
`{{type}}` is `Main menu`, `Sub menu` or `Page`
`{{displayTitle}}` is the normalized `displayTitle`
Types are translatable at:
`_globals._accessibility._ariaLabels.course = "Main menu"`
`_globals._accessibility._ariaLabels.menu = "Sub menu"`
`_globals._accessibility._ariaLabels.page = "Page"`
* Added topOfContentObject functionality which inserts an element at the top of the page, the element is updated and focused when routing
I have done:
* …

New: Focus at top of page when routing (fixes #626)

---

less/core/drawer.less

Fix #659 
* Prevent `.drawer` from scrolling. Instead, we will rely on `.drawer__holder` for the scrolling container.
1. Install `adapt-contrib-glossary`
2. Add a large amount of glossary items (30+)
3. Scroll down to the end of the list. Ensure that you cannot scroll past the last item.

Fix: Fix drawer overflow issue with scrolling(fixes #659)

---

js/views/drawerView.js
js/views/navigationView.js
templates/nav.hbs

- For navigation buttons that trigger a dialog to open (Notify popup or Drawer), the button `aria-expanded` has been replaced with `aria-haspopup="dialog"`.  Please refer to the [issue](https://github.com/adaptlearning/adapt-contrib-core/issues/657) for the research and discussion supporting this change. 
Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/657
- Remove `aria-expanded` from Drawer `<dialog>` as this serves no purpose and it is not the intended use. See [MDN note](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-expanded#:~:text=When%20the%20popup%20element%20is,should%20be%20set%20to%20true%20.&text=Note%3A%20The%20presence%20of%20the,expanded%20state%20of%20other%20elements) for reference below or refer to the …

Update: Replace dialog button aria-expanded with aria-haspopup dialog (fixes #657)

---

js/enums/completionStateEnum.js
js/models/questionModel.js
js/views/questionView.js

Fixes #669.
* Added contextActivities API for adding context to questions for reporting purposes
* xAPI and SCORM handle this differently so their relevant plugins can choose to use and expand on the base data as required for each spec
* Added `UNKNOWN` to https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/enums/completionStateEnum.js

New: contextActivities API for adding context to questions for reporting purposes
