adaptlearning/adapt-contrib-core

js/a11y.js, js/enums/defaultAriaLevels.js, js/helpers.js
fixes #4 
* Moved aria level calculation from `a11y_attrs_heading` helper to `Adapt.a11y.ariaLevel`
* Fixed some linting issues
=> issue/4 Added Adapt.a11y.ariaLevel

js/models/adaptModel.js
fixes #2 
* Locking is aware of previous locking state, if the previous item _isLocked then this item will be locked
=> issue/2 Check all previous locks

js/a11y/browserFocus.js
fixes #8 
* Removed defer from tabindex removal
=> issue/8 Synchronous removal of tabindex on forced focus elements

templates/image.jsx
Resolves https://github.com/adaptlearning/adapt-contrib-core/issues/13
* Amended selector typos
=> Selector typo fix

templates/image.jsx
fixes #28 
* If no medium property exsits, make sure to use small image for medium sizes
=> issue/28 image.jsx large/small and large/medium/small

js/models/questionModel.js
=> Consider falsey nature of 0 attempts

js/views/buttonsView.js, package.json
=> greater than 0 check for 'attempts remaining' button text display

js/models/itemsQuestionModel.js
fixes #40 
* Score sorting to pick highest and lowest scores
=> issue/40 Fixed _hasItemScoring

js/tracking.js, package.json
Fixes https://github.com/adaptlearning/adapt_framework/issues/2604
See https://github.com/adaptlearning/adapt-contrib-spoor/pull/222
=> #2604 ensure score sent to LMS before status

js/adapt.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3231
* Allow plugins to wait after `adapt:preInitialize`, `adapt:start` and `adapt:initialize`
=> issue/3231 Added adapt loading wait queues

js/tracking.js, schema/config.schema.json
https://github.com/adaptlearning/adapt-contrib-core/issues/55
* Moved _shouldSubmitScore into core and core schema with backward compatibility for the spoor version
=> issue/55 Backward compatibility for _shouldSubmitScore

js/tracking.js
Move the check for _requireAssessmentCompleted to onAssessmentComplete. Fix for #55
=> Allow score to be set if _requireAssessmentCompleted is false

js/views/questionView.js
fixes #60
* QuestionView removeInstructionError
=> Removing Instruction Error Functions

js/models/itemsQuestionModel.js
fixes #41 
* Compile directive for ItemsQuestionModel item specific feedback text
=> issue/41 Added compile to ItemsQuestionModel item specific feedback text

js/views/navigationView.js, schema/course.model.schema, schema/course.schema.json, templates/nav.hbs
part of https://github.com/adaptlearning/adapt_framework/issues/3281
* Allowed the sorting of navigation buttons according to a `data-order` attribute in the dom
* `data-order` attribute to drawer nav bar button
=> issue/3281 Added data-order to buttons for sorting navigation

js/models/questionModel.js
fixes #67 
* Update `_shouldShowMarking` in `setQuestionAsReset` and `setQuestionAsSubmitted` functions
=> issue/67 Update _shouldShowMarking properly

libraries/inview.js
https://github.com/adaptlearning/adapt-contrib-core/issues/63.
=> issue/63 Fix for inview percentages

libraries/inview.js
https://github.com/adaptlearning/adapt-contrib-core/issues/64
=> Fix for fullscreen inview elements

js/models/questionModel.js
fixes #71 
* Deprecated `setScore`
=> issue/71 Deprecate setScore

js/device.js
https://github.com/adaptlearning/adapt-contrib-core/issues/75
=> ADAPT-9842-include iPad device check

schema/course.schema.json
fixes https://github.com/adaptlearning/adapt_framework/issues/2589
* Corrected property name
=> issue/2589 fixed drawer _navOrder in schema

js/models/questionModel.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3279
* Reset _isCorrectAnswerShown appropriately
=> issue/3279 Reset _isCorrectAnswerShown in question

js/router.js
fixes #82 
fixes https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/112
* Router will move to another page even if it has a view rendered in the current page
=> issue/82 Fixed router for menuItemView

js/a11y.js
fixes #89 
fixes https://github.com/adaptlearning/adapt_framework/issues/3176
* Changed to tabindex=0 from tabindex=-1 where focus is forced on a nonfocusable element
=> issue/89 Fixed JAWS reading forced focus

required/adapt/js/scriptLoader.js
fixes #80 
* Removed requirejs module timeout for slow connections [reference](https://requirejs.org/docs/api.html#config-waitSeconds)
=> issue/80 Set waitSeconds to 0 requirejs

js/views/headingView.js
fixes #91 
* Use the menu aria-level for the course menu
=> issue/91 Use menu aria-level for course

js/models/adaptModel.js, js/models/itemsComponentModel.js, js/views/adaptView.js
fixes #97 
* Visited state save/restore and handlers
* setReadyStatus and setCompletionStatus functions use model versions
=> issue/97 Added _isVisited to trackable properties and cascade

js/views/notifyView.js
fixes #114 
* `notify.isOpen` to signify if any notifies are open
=> issue/114 Added notify.isOpen

js/data.js, js/router.js
fixes #120 
* Function was not treating selectors correctly
* `data.hasId` to check if an id exists
=> issue/120 Fixed router.navigateToElement with selectors

js/models/componentModel.js, js/models/questionModel.js
fixes #117 
* `_shouldStoreAttempts` to prevent individual questions attempting to add to their attempt history
=> issue/117 Added _shouldStoreAttempts

js/a11y.js
fixes #104 
* Function to turn on and off tabindexes on all descendants
=> issue/104 Added toggleTabbableDescendants

js/helpers.js
adding in missing tabindex
Fixes #140
=> issue/140 Fixed focuswrap tab index

templates/drawer.hbs
fixes #101
Reverses order of toolbar vs drawer holder. #101
=> issue/101 Reverses focus order of drawer holder & header

templates/heading.hbs
=> Adjusts context between header & status in aria-labels

README.md, js/views/notifyPopupView.js, package.json
=> Append subview rather than prepend

templates/notifyPopup.hbs, templates/notifyPush.hbs
Resolves https://github.com/adaptlearning/adapt-contrib-core/issues/139
* Converted button divs to spans
=> Converted notify button divs to spans

schema/config.schema.json, schema/content.schema.json, schema/contentobject.schema.json, schema/course.schema.json
fixes #143
Remove unnecessary required defs
=> Remove unnecessary required definitions from schemas

js/router.js
fixes #169 
* Allowed navigateToElement to take a jquery array
=> issue/169 router.navigateToElement jquery object fix

required/index.html
part of https://github.com/adaptlearning/adapt_framework/issues/3311
* Removed unnecessary type attribute on script tags
=> issue/3311 Removed unnecessary type attribute on script tags

js/components.js, js/data.js, js/models/configModel.js, js/views/contentObjectView.js
fixes #119 
* id checking
* trackingid checking
* _isReady error
* file loading errors
* file data errors
=> issue/119 Introduced better loading failure warnings

schema/config.schema.json
=> Update _ariaLevels to use relative strings

js/device.js
fixes #209 
* Changed device resize html classes changes to occur on animation frames as soon as possible
=> Fix: Device resize html classes rendering speed (fixes #209)

js/device.js, less/_defaults/_variables.less
fixes #175.
* CSS properties for viewport height
Ref: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty
=> New: `--adapt-viewport-height` to aid viewport height positioning (fixes #175)

js/adapt.js, js/models/adaptModel.js
fixes #227
* `findRelativeModel` can now perform multiple directives
* `findRelativeModel` can now also search for children, forwards and backwards by incremenet
=> New: Extended findRelativeModel (fixes #227)

js/views/adaptView.js
fixes #225 
* Added role=presentation to AdaptView
Reference:
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role
* https://github.com/facebook/react/issues/20895#issuecomment-1021175889
=> Fix: NVDA reads clickable (fixes #225)

js/models/questionModel.js, js/views/questionView.js
fixes #196
* Added model property `_isPartlyCorrect` and view event `questionView:submitted` to the question API
=> Update: _isPartlyCorrect and questionView:submitted (fixes #196)

js/views/drawerView.js, templates/nav.hbs
fixes #103 
* Added aria-expanded state to drawer navigation button and toggled accordingly
=> Fix: aria-expanded state to drawer button (fixes #103)

js/a11y.js, js/helpers.js
fixes #229
* Fixed aria-level template string 
* Linting
=> Fix: Automated aria-levels bug (fixes #229)

js/deprecated.js, js/drawer.js, js/views/drawerItemView.js, js/views/drawerView.js, js/views/navigationView.js, less/core/drawer.less, schema/config.model.schema, schema/config.schema.json, templates/nav.hbs
fixes #216 
fixes #217 
fixes #218 
* Reworked main file into a proper controller with defined API
* Added `_drawer._position = "auto|left|right"` to `config.json`
* Added `drawer.isOpen`
* Prevent duplicate items
=> New: Drawer position, drawer API refactor (fixes #216, #217, #218)

schema/config.schema.json
Fixes #266
Add missing curly bracket to new property added in [`0a0f3aa`](https://github.com/adaptlearning/adapt-contrib-core/commit/0a0f3aa2690521085c79831b3902a7548f21049e#diff-f712d6d3c285eaed759e9093d238a3a89de99f186f853fd10cc0426b0672149a)
=> Fix: Add missing curly bracket (fixes #266)

js/templateRenderEvent.js
fixes #241
* Reverted to vanilla class from backbone controller
=> Fix: Performance enhancement to template events (fixes #241)

js/data.js
fixes #253 
* Reset _byAdaptID on load manifest files
=> Fix: Reset _byAdaptID on load manifest files (fixes #253)

js/navigation.js, less/core/nav.less, schema/course.model.schema, schema/course.schema.json
fixes #165 
* `_navigation._navigationAlignment` option and behaviour to allow navigation bar to appear at the bottom rather than the top
* `_navigation._isBottomOnTouchDevices` bottom only on touch devices
use with https://github.com/adaptlearning/adapt-contrib-trickle/pull/162
=> New: Added bottom navigation settings (fixes #165)

js/views/contentObjectView.js
fixes #224 
* Corrected check for jsx template
=> Fix: Corrected check for jsx template (fixes #224)

less/core/nav.less
Fixes: #231 
* Converted `:focus` to `:focus-visible`
=> Update: Updated focus to focus-visible (fixes #231)

js/deprecated.js
Fixes (https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/issues/157 https://github.com/adaptlearning/adapt-contrib-core/issues/276)
* Error in deprecated logging for drawer which meant the drawer wasn't closing correctly (#276)
1. Open PLP from a page
2. Select a component
=> Fix: Error in deprecated logging for drawer (#276)

schema/course.model.schema, schema/course.schema.json
* Fixes #286 
* Adds help & description fields in the schemas for navigation buttons
1. Upload new core to AAT
2. Test to see that descriptors have been added.
Currently unable to test this in v1 AAT instance.
=> Fix: Adds navOrder descriptions (fixes: 286)

js/models/questionModel.js
Fixes: #288
* Fix: Feedback title has default fallbacks
=> Fix: Applying fallback title settings for feedback

js/views/questionView.js
=> Fix: restore responses for incomplete questions

js/views/notifyPushView.js
Please see the issue raised here https://github.com/adaptlearning/adapt-contrib-core/issues/295
=> #295 - Issue with classes that are applied to the notify-push element

templates/drawer.hbs, templates/nav.hbs, templates/notifyPopup.hbs, templates/notifyPush.hbs
* Fixes #301 
1. Pull down this PR and examine the structure in the output
=> Fix: Normalize icons globally (fixes: #301)

js/views/headingView.js, templates/header.jsx
Fixes: #314 
* Add support in the header template for extensions
=> Fix: Add header template support for extensions (fixes: #314)

js/a11y.js
fixes #292 
* Switch to native js in isReadable visibility detection, bug with jquery in chrome
=> Fix: Switch to native js in isReadable visibility detection

js/models/questionModel.js
* Fixes #323 
1. Pull down and compile the FW.
=> Fix: questionModel.js syntax (fixes: #323)

package.json
#331 
* Removing 'skip-ci' element of commit message for semantic release tags
=> Fix: Removing 'skip-ci' element of commit message for semantic release tags

js/models/adaptModel.js
Fixes #335
* Added a successful `'reset'` event trigger for AdaptModel
=> New: added successful reset event trigger (fixes #335)

js/models/questionModel.js
#334 
* Feedback incorrect not final should fall back to feedback incorrect final value if not set itself
1. Create a course with question component and tutor
2. Allow multiple attempts on question, but do not populate incorrect not final value
3. Feedback body is empty
=> Fix: Feedback incorrect not final should use fallback

js/data.js
fixes #188 
* The `app:languageChange` event now has two attributes when the language is changing and not just loading.
`app:languageChanged(selectedLanguage)` Will trigger when the course loads
`app:languageChanged(newLanguage, previousLanguage)` Will trigger when the language is changed
=> Update: Added change vs initial language selection attribute

schema/config.model.schema, schema/config.schema.json
fixes #380
Update to title text
=> Fix: Updated title text in schemas

js/a11y.js, js/a11y/scroll.js
fixes #378 
* `input[type=radio]` in popup bug
* Added `a11y.isArrowable`
=> New: Added isArrowable and fixed input[type=radio] in popup bug

js/models/adaptModel.js, js/router.js
fix #393 
* Added _isRendered: true to the main view render
=> Fix: Added _isRendered: true to main view render

templates/header.jsx
Resolves: #395 
* Allow custom classes to be passed through from plugins to the header template
=> Update: Added header custom class support (fixes #395)

js/views/drawerView.js
Fixes: #409 
* Set the aria-expanded attribute appropriately on the drawer
=> Fix: Set aria-expanded attribute true/false to match drawer visibility

js/startController.js
Fixes #412.
* Trickle incorrectly unlocking when switching languages
* Minor code refactor
* Reduced routing on launch
=> Fix: trickle incorrectly unlocking when switching languages

js/views/TooltipView.js
#426 
* onAdaptPreInitialize updated to only run on initial load (fixes #426 )
=> Fix: onAdaptPreInitialize updated to only run on initial load (#426)

.github/workflows/frameworkpullrequest.yml
#440 
* Core version added to automatic framework release (fixes #440)
=> Fix: Core version added to automatic framework release (#440)

templates/page.hbs
Fixes: #449
* Added new content container element to page template
=> Update: Added content container element (fixes #449)

js/models/itemsQuestionModel.js
fixes #454 
* Coerce `_isAtLeastOneCorrectSelection` to boolean
=> Fix: Boolean _isAtLeastOneCorrectSelection (fixes #454)

js/tracking.js
fixes #474 
* Correctly set _isAssessmentPassed as it had been mistakenly removed
=> Fix: Set _isAssessmentPassed correctly (fixes #474)

less/core/button.less, less/core/component.less, less/core/drawer.less, less/core/nav.less, less/core/tooltip.less
Fixes #480 
* Updated RTL styling to remove unnecessary declarations
=> Update: Updated RTL styling (fixes #480)

js/router.js
fixes #488
* Allow urls of the format /#/preview/b-05 for rendering a single id, the rendered content is a linked clone to the original
Works best with:
https://github.com/adaptlearning/adapt-contrib-core/pull/494
https://github.com/adaptlearning/adapt-contrib-core/pull/492
https://github.com/adaptlearning/adapt-contrib-core/pull/490
https://github.com/adaptlearning/adapt-contrib-narrative/pull/296
https://github.com/adaptlearning/adapt-contrib-trickle/pull/211
Jump between components/blocks/articles by using the urls below. The components should be synced in most cases. Narrative and trickle require some bugs fixes, given above.
Preview renders just the specified id:
```
#/preview/b-35
```
Normal routing renders and jumps to the specified id in the normal context:
```
#/id/b-35
```
=> New: Allow /#/preview/b-05 for rendering a single id (fixes #488)

js/models/componentModel.js
fixes #491 
* Restores user answers on setAttemptObject
=> Fix: Restore user answers on setAttemptObject (fixes #491)

required/index.html
fixes #499 
* Set initial html lang and dir attributes from _defaultLanguage and _defaultDirection in config.json
=> Fix: set html lang and dir attributes from config.json (fixes #499)

js/models/itemsQuestionModel.js
fixes #507 
* missing _userAnswer in restoreUserAnswers
* getFeedback missing activeItem
=> Fix: Missing object property lookup restoreUserAnswers, getFeedback, ItemsQuestionModel (fixes #507)

js/helpers.js
fixes #504
* Added use helper to allow ```{{#use 'c-200'}}{{{feedbackMessage}}}{{/use}}```
=> New: Added use helper (fixes #504)

schema/course.model.schema, schema/course.schema.json
Fixes #520 
* New "mandatory" and "optional" labels added to _ariaLabels in the course schema. Updates to the page template and Boxmenu will follow.
=> Mandatory and optional labels added to schema (fixes #520)

js/views/questionView.js
Fixes #530 
* Typo correction for logged deprecation warning
=> Fix: Typo correction for logged deprecation warning [530]

js/router.js
Addresses #556 
* Flag when routing isPreviewMode and reusing common functionality
=> Update: Flag when routing isPreviewMode and reusing common functionality

js/router.js
#566 
* reset location info on changing language
=> Fix: reset location info on changing language (fixes #566)

js/views/navigationView.js
fixes #564 
* Recalculate nav height on button addition
=> Fix: Recalculate nav height on button addition

schema/contentobject.schema.json, schema/course.schema.json
#604 
* isObjectId removed from schema to allow external assets to be added (fixes #604)
=> Fix: isObjectId removed from schema to allow external assets to be added (fixes #604)

libraries/inview.js
#612
* Return early if trying to process inview handlers whilst locked
=> Fix: inview respecting locks on window resize (#612)

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_template.md
Fixes https://github.com/adaptlearning/adapt-contrib-core/issues/618
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
=> Chore: Add support for new issue experience (fixes #618)

less/core/nav.less, less/core/scrolling.less, required/index.html
Fixes #653 
* Add a static `html` class the html element
=> Fix: Add html class to html element (fixes #653)

migrations/v2.js, migrations/v3.js, migrations/v4.js, migrations/v5.js, migrations/v6.js
#634 
* Core migration scripts added (fixes #634)
=> New: core migration scripts added (fixes #634)

js/views/notifyPopupView.js, js/views/notifyPushView.js
fixes #646 
* Escape key closes only focused notify
=> Fix: Escape key closes only focused notify (fixes #646)

js/router.js
fixes #644 
* Added `model.isTypeGroup('group')` to tell the router that a contentobject is a sub-part of its parent and not a main contentobject
* Added `router.addRouteToHistory(hash)` to force the router to better track sub-contentobject navigation
* Allow the router to navigate to sub-contentobject parts without re-rendering the contentobject
* The router now waits for the contentobject to become ready before assigning focus or navigating to a sub-part
* Renamed `router.isScrolling` to a more appropriate `router._isInNavigateTo`
* The router now adds sub-contentobject navigations to the url history
=> New: Content object typegroup=group, router.addRouteToHistory (fixes #644)

migrations/v6.js, schema/article.model.schema, schema/block.model.schema, schema/component.model.schema, schema/content.schema.json, schema/contentobject.model.schema
Fixes #625
* Adds `_ariaLevel` to core schemas
* Adds required migration scripts
=> New: Add _ariaLevel to core schemas (fix #625)
